### ISSUE TITLE
Cannot create client endpoint using TorClientEndpointParser

### ISSUE THREAD

**Issue by DonnchaC** [meejah/txtorcon#124]
It appears that `clientFromString()` does not work for creating a Tor client endpoint. I'm looking at this with @david415 and he asked to open a ticket

```
tor:host=3g2upl4pq6kufc4m.onion:port=443
Unhandled Error
Traceback (most recent call last):
  File "~/<~snip~>/local/lib/python2.7/site-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "~/<~snip~>/local/lib/python2.7/site-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "~/<~snip~>/local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "~/<~snip~>/local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "~/<~snip~>/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "~/<~snip~>/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 209, in doRead
    return self._dataReceived(data)
  File "~/<~snip~>/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 215, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "basicmitmproxy.py", line 87, in dataReceived
    endpoint = clientFromString(reactor, endpoint_string)
  File "~/<~snip~>/local/lib/python2.7/site-packages/twisted/internet/endpoints.py", line 1760, in clientFromString
    raise ValueError("Unknown endpoint type: %r" % (aname,))
exceptions.ValueError: Unknown endpoint type: 'tor'
```

**Comment by david415** [comment]
i can't find the problem in txtorcon; it has a proper setup.py which causes the twisted plugins to be installed... and as far as i can tell it *should* work. however we noticed that using my older prototype api txtorsocksx worked in @DonnchaC 's python virtual env:

pip install git+https://github.com/david415/txtorsocksx.git

after installing the "tor" endpoint parser was available to twisted programs via clientFromString.

I think we should include some tor client examples in txtorcon... and then we can also run them to make sure it all works; sorta like having integration tests.

**Comment by meejah** [comment]
I agree re integration tests and example(s).

There actually are a couple integrarion tests based on docker containers but dont get run by default in Travis builds. Could it be that yoy have to do "something special" if there are > 1 plugins?

**Comment by meejah** [comment]
I tried a simple example, after installing a fresh checkout via ``pip install -e path/to/checkout`` and it seems to work (at least as far as parsing the endpoint string):

```python
ep = clientFromString(reactor, "tor:host=timaq4ygg2iegci7.onion:port=80")                                                                 
print(ep)
print(type(ep))
```

This was with Twisted 15.3.0

**Comment by david415** [comment]
we clearly were doing something wrong; it works for us after rebuilding our virtual envs.

**Comment by DonnchaC** [comment]
Seems like I was doing something wrong, all working now. Than
