### ISSUE TITLE
Three tests errors (test_attribute_access, test_other_bootstrap, and ProtocolIntegrationTests.test_with_arg)

### ISSUE THREAD

**Issue by mcepl** [meejah/txtorcon#362]
While packaging txtorcon for openSUSE/Factory these tests are erroring (using Twisted 21.7.0):
```
[  157s] [ERROR]
[  157s] Traceback (most recent call last):
[  157s]   File "/usr/lib/python3.6/site-packages/twisted/internet/defer.py", line 63, in run
[  157s]     return f(*args, **kwargs)
[  157s]   File "/home/abuild/rpmbuild/BUILD/txtorcon-20.0.0/test/test_torinfo.py", line 169, in test_attribute_access
[  157s]     yield self.protocol.post_bootstrap
[  157s]   File "/usr/lib/python3.6/site-packages/twisted/internet/defer.py", line 859, in _runCallbacks
[  157s]     current.result, *args, **kwargs
[  157s]   File "/home/abuild/rpmbuild/BUILD/txtorcon-20.0.0/txtorcon/torinfo.py", line 285, in _setup_complete
[  157s]     pb.callback(self)
[  157s]   File "/usr/lib/python3.6/site-packages/twisted/internet/defer.py", line 661, in callback
[  157s]     assert not isinstance(result, Deferred)
[  157s]   File "/usr/lib64/python3.6/typing.py", line 1162, in __instancecheck__
[  157s]     return issubclass(instance.__class__, self)
[  157s]   File "/home/abuild/rpmbuild/BUILD/txtorcon-20.0.0/txtorcon/torinfo.py", line 213, in __getattribute__
[  157s]     raise AttributeError(name)
[  157s] builtins.AttributeError: __class__
[  157s]
[  157s] test.test_torinfo.InfoTests.test_attribute_access
[  157s] ===============================================================================
[  157s] [ERROR]
[  157s] Traceback (most recent call last):
[  157s]   File "/home/abuild/rpmbuild/BUILD/txtorcon-20.0.0/txtorcon/torinfo.py", line 285, in _setup_complete
[  157s]     pb.callback(self)
[  157s]   File "/usr/lib/python3.6/site-packages/twisted/internet/defer.py", line 661, in callback
[  157s]     assert not isinstance(result, Deferred)
[  157s]   File "/usr/lib64/python3.6/typing.py", line 1162, in __instancecheck__
[  157s]     return issubclass(instance.__class__, self)
[  157s]   File "/home/abuild/rpmbuild/BUILD/txtorcon-20.0.0/txtorcon/torinfo.py", line 213, in __getattribute__
[  157s]     raise AttributeError(name)
[  157s] builtins.AttributeError: __class__
[  157s]
[  157s] test.test_torinfo.InfoTests.test_other_bootstrap
[  157s] ===============================================================================
[  157s] [ERROR]
[  157s] Traceback (most recent call last):
[  157s] Failure: twisted.internet.defer.TimeoutError: <test.test_torinfo.ProtocolIntegrationTests testMethod=test_with_arg> (test_with_arg) still running at 120.0 secs
[  157s]
[  157s] test.test_torinfo.ProtocolIntegrationTests.test_with_arg
[  157s] -------------------------------------------------------------------------------
[  157s] Ran 680 tests in 121.302s
[  157s]
[  157s] FAILED (skips=8, errors=3, successes=669)
[  157s] /usr/lib/python3.6/site-packages/twisted/trial/__main__.py:5: UserWarning: Module twisted was already imported from /usr/lib/python3.6/site-packages/twisted/__init__.py, but /home/abuild/rpmbuild/BUILD/txtorcon-20.0.0 is being added to sys.path
[  157s]   from pkg_resources import load_entry_point
[  157s] error: Bad exit status from /var/tmp/rpm-tmp.rCF9XM (%check)
```

[Complete build log](https://github.com/meejah/txtorcon/files/7085266/_log.txt) with all details of steps taken and packages used.

**Comment by meejah** [comment]
It was recently discovered some tests weren't running properly due to imports .. e.g. https://github.com/meejah/txtorcon/issues/356

Does using 21.1.0 fix these issues for you?

**Comment by mcepl** [comment]
Yes, it does. SOrry, for missing that.

**Comment by meejah** [comment]
great, thanks!
